---
galaxy_info:
  author: Emrecan Altinsoy
  description: Git configuration with SSH key management
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - git
    - ssh
    - security

dependencies:
  - base
