---
# Debian/Ubuntu specific tasks

- name: Update apt dependencies
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  failed_when: false

- name: Install apt dependencies
  become: true
  ansible.builtin.apt:
    name:
      - bat
      - build-essential
      - curl
      - fd-find
      - git
      - jq
      - keychain
      - openssh-client
      - python3
      - python3-pip
      - python3-venv
      - python3-wheel
      - python3-dev
      - ripgrep
      - socat
      - software-properties-common
      - stow
      - unzip
      - wget
      - zip
      - zoxide
      - zsh
    state: present

- name: Install fastfetch (Ubuntu 23.04+)
  become: true
  ansible.builtin.apt:
    name: fastfetch
    state: present
  failed_when: false
