---
# Debian/Ubuntu cargo packages

- name: Define cargo packages to install
  ansible.builtin.set_fact:
    cargo_packages:
      - name: exa
        bin: exa
        skip_id: exa
      - name: git-delta
        bin: delta
        skip_id: git_delta
      - name: rm-improved
        bin: rip
        skip_id: rm_improved
      - name: topgrade
        bin: topgrade
        skip_id: topgrade
      - name: xcp
        bin: xcp
        skip_id: xcp
      - name: yazi-fm
        bin: yazi
        skip_id: yazi
      - name: procs
        bin: procs
        skip_id: procs
      - name: tokei
        bin: tokei
        skip_id: tokei
      - name: xh
        bin: xh
        skip_id: xh
      - name: zellij
        bin: zellij
        skip_id: zellij
      # zoxide available in apt, skip here
