#!/usr/bin/env bash

. $HOME/.dmenu-scripts/dmenu-config/config
. $HOME/.dmenu-scripts/dmenu-config/dmenu-theme

main() {
  bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | ${DMENU} $colors $font -p "Select Wifi  :" -l 20 | cut -d' ' -f1)
  if [ "$bssid" ]; then
    pass=$(echo "" | ${DMENU} -p "Enter Password  :")
    if [ "$pass"  ]; then
      nmcli device wifi connect "$bssid" password "$pass"
      sleep 10
      if ping -q -c 2 -W 2 google.com >/dev/null; then
        notify-send "Your internet is working :)"
      else
        notify-send "Your internet is not working :("
      fi
    fi
  fi
  echo "Program terminated." && exit 0
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"

