#!/usr/bin/env bash

# dmenu theme
. $HOME/.dmenu-scripts/dmenu-config/dmenu-theme
colors="-nb #2C323E -nf #9899a0 -sb #BF616A -sf #2C323E"

main() {
    selected="$(ps -a -u $USER | \
                dmenu -i -p "Type to search and select process to kill" \
                -l 10 $colors $font | \
                awk '{print $1" "$4}')"; 

    if [[ ! -z $selected ]]; then
        answer="$(echo -e "Yes\nNo" | \
                dmenu -i -p "$selected will be killed, are you sure?" \
                $lines $colors $font )"

        if [[ $answer == "Yes" ]]; then
            selpid="$(awk '{print $1}' <<< $selected)"; 
            kill -9 $selpid
        fi
    fi
    echo "Program terminated." && exit 0
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"

