#!/usr/bin/env bash

. $HOME/.dmenu-scripts/dmenu-config/config
. $HOME/.dmenu-scripts/dmenu-config/dmenu-theme

main() {
  # Clean options array making sure that the files exist
  declare -A _clean_list
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154
  for i in "${!confedit_list[@]}"; do
    [[ -f ${confedit_list["${i}"]} ]] && _clean_list["${i}"]=${confedit_list["${i}"]}
  done

  # Piping the above array (cleaned) into dmenu.
  # We use "printf '%s\n'" to format the array one item to a line.
  choice=$(printf '%s\n' "${!_clean_list[@]}" | sort | ${DMENU} -i -l 20 $colors $font -p 'Edit config:' "$@")

  # What to do when/if we choose a file to edit.
  if [ "$choice" ]; then
    cfg=$(printf '%s\n' "${_clean_list["${choice}"]}")
    # shellcheck disable=SC2154
    $confedit_editor "$cfg"
  fi
  # What to do if we just escape without choosing anything.
  echo "Program terminated." && exit 0
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"

